baseURL = "https://sayymeer.github.io/"
locale = "en-us"
title = "sayymeer"
theme = "PaperMod"
paginate = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "Sameer"
  description = ""
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  math = true

[params.homeInfoParams]
  Title = "Hi, I'm Sameer"
  Content = "Undergraduate @ IIT Kanpur"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/sayymeer"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sameeryadav08/"


[taxonomies]
  tag = "tags"

[[menu.main]]
  identifier = "whoami"
  name = "whoami"
  url = "/whoami/"
  weight = 10

[[menu.main]]
  identifier = "uses"
  name = "uses"
  url = "/uses/"
  weight = 10



[[menu.main]]
  identifier = "cv"
  name = "cv"
  url = "/cv/"
  weight = 10


[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "search"
  url = "/search/"
  weight = 30
